### ISSUE TITLE
link

### ISSUE THREAD

**Issue by andriipalchik** [ruby/TryRuby#19]
Hello there! One little issue: you have https://opalrb.org on the "about" and "app-development" pages of the tutorial, while there must be http://opalrb.com Bad link goes to Casinos. Cheers!)

**Comment by easydatawarehousing** [comment]
Thanks. I have already changed these links. The [fork of tryruby](https://github.com/ruby/TryRuby) needs to sync these changes. I will ask @hsbt

**Comment by hsbt** [comment]
I fixed at https://github.com/ruby/TryRuby/commit/e47ae0dbdcc78c20bbb6d7672d628b432d46ffc1

Thanks.

**Comment by Ueeu** [comment]
... I still get a link to http://opalrb.org/ on https://ruby.github.io/TryRuby/about/ - but the rest of the site is great...

**Comment by geeksam** [comment]
I'm also still seeing the old link.  It's fixed in source, so... is the Middleman site build skipping that page somehow?

**Comment by easydatawarehousing** [comment]
Updated.
